### ISSUE TITLE
请问你能提供修改完的nmap-service-probes吗

### ISSUE THREAD

**Issue by ghost** [al0ne/Nmap_Bypass_IDS#4]
由于不只要修改probe的参数，还要改相对映的match参数，实在太麻烦。所以能否给个您修改后的service-probes版本呢 

希望你能帮忙，提前致谢

**Comment by ghost** [comment]
我还是自己努力一行一行改，不劳烦作者了。
另外你在Readme.md中的“修改nmap-service-probes”中提到去掉Options sip，但Options sip是用来OS detection，你没说清楚，很多脚本小子乱删一通，会让他们误解啊！
正确方法应该是修改probe 中的nm,nm@nm等关键字，推荐使用notepad++查询和修改

**Comment by Bit-flipper** [comment]
如果我有时间修改完，我会pull我的版本

**Comment by Bit-flipper** [comment]
如果我有时间修改完，我会pull我的版本

**Comment by al0ne** [comment]
感谢提醒！ 另外不需要一行一行修改 可以先根据Suricata开源规则里面关于Nmap的检测规则修改对应的值

**Comment by ghost** [comment]
我有时间时看了一下，在notepad++的帮忙下只消几分钟就改完了，我这边就不pull我的版本了。还有，感谢作者思路提供，给了一篇好文
